---
title: "EE283_Assignment2"
author: "Josh Crapser"
date: "January 16, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
data <- read_delim("data.txt", delim="\n")
data$value <- as.double(data$value)
```

## Generate the output data frame using Base R:

```{r baseR}
data$temp <- rep(0) #create temporary column to hold distance values
data$closest <- rep(0) #create the column that will indicate index of closest non-zero value
for (i in seq_along(data$value)) { #loop over every index of data column
  if (data$value[i] == 0){ #if value is 0...
    for (x in which(data$value>0)) { #..for all indices containing a non-zero value..
      data$temp[x] <- (abs(x-i)) #..calculate absolute difference between current index and non-zero indices
      data$temp[data$temp == 0] <- NA #replace all 0 values with NA in temp column
      data$closest[i] <- (which.min(data$temp)) #find minimum difference between current index and non-zero index, the closest non-zero index will be assigned to the row in data$closest
    }
  } else {
    data$closest[i] <- i #if value is non-zero in data$value, keep value
  }
}
data$temp <- NULL
data$nonzero <- NULL
print(data) #remove temp columns and print table
```

## Generate the output data frame using tidyverse:

```{r tidyoutput}

data %>% mutate(row_num = row_number()) %>% mutate(null = na_if(data$value,0)) %>% mutate(closest = min(abs(row_num[null=1]-data$value)))
```